# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven core"
  homepage: https://maven.apache.org/ref/current
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - hacktoberfest
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira:
    - MNG
  pull_requests:
    del_branch_on_merge: true
  protected_branches:
    master: {}
    maven-4.0.x: {}
    maven-3.9.x: {}
    maven-3.8.x: {}
    maven-3.0.x: {}
    pre-reset-master: {}
  features:
    issues: true
notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org
