# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven core"
  homepage: https://maven.apache.org/ref/current
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - hacktoberfest
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira:
    - MNG
  pull_requests:
    del_branch_on_merge: true
  protected_branches:
    master: {}
    maven-4.0.x: {}
    maven-3.10.x: {}
    maven-3.9.x: {}
    maven-3.8.x: {}
    maven-3.0.x: {}
    maven-2.2.x: {}
    pre-reset-master: {}
  features:
    issues: true
notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org

# https://release-test.apache.org/projects/maven
project:
  metadata:
    key: maven
    committee: maven
    name: Apache Maven
    description: "Maven is a project development management and comprehension tool.
      Based on the concept of a project object model: builds, dependency management,
      documentation creation, site publication, and distribution publication are all controlled from the declarative file.
      Maven can be extended by plugins to utilise a number of other development tools for reporting or the build process."
    short_description: Maven is a project development management and comprehension tool.
    homepage: https://maven.apache.org/
    download_page: https://maven.apache.org/download.html
    bug_database: https://github.com/apache/maven/issues
    mailing_lists: https://maven.apache.org/mailing-lists.html
    repositories:
      - https://github.com/apache/maven.git
    categories:
      - build-management
    programming_languages:
      - Java
  policy:
    github_repository_name: maven
    download_path_suffix: maven-{{MAJOR_VERSION}}/{{VERSION}}
  features:
    atr_sync: true
