#!/bin/bash

# Test script demonstrating the new cache configuration functionality

echo "Maven Cache Configuration Enhancement Test"
echo "=========================================="

echo ""
echo "1. Basic Configuration Test:"
echo "   Setting ModelBuilderRequest to use session scope with hard references"
echo "   Command: mvn clean compile -Dmaven.cache.config=\"ModelBuilderRequest { scope: session, ref: hard }\""
echo ""

echo "2. Partial Configuration Test:"
echo "   Setting only scope for ModelBuilderRequest (ref will use default)"
echo "   Command: mvn clean compile -Dmaven.cache.config=\"ModelBuilderRequest { scope: session }\""
echo ""

echo "3. Merging Configuration Test:"
echo "   Base configuration + specific override"
echo "   Command: mvn clean compile -Dmaven.cache.config=\""
echo "   ModelBuilderRequest { scope: session }"
echo "   * ModelBuilderRequest { ref: hard }"
echo "   ModelBuildRequest ModelBuilderRequest { ref: soft }"
echo "   \""
echo ""

echo "4. Parent-Child Relationship Test:"
echo "   Different behavior based on parent request type"
echo "   Command: mvn clean compile -Dmaven.cache.config=\""
echo "   ModelBuilderRequest { scope: session, ref: soft }"
echo "   ModelBuildRequest ModelBuilderRequest { ref: hard }"
echo "   \""
echo ""

echo "5. Wildcard Configuration Test:"
echo "   Apply weak references to all requests with any parent"
echo "   Command: mvn clean compile -Dmaven.cache.config=\"* * { ref: weak }\""
echo ""

echo "6. Disable Caching Test:"
echo "   Disable caching for specific request types"
echo "   Command: mvn clean compile -Dmaven.cache.config=\"VersionRangeRequest { scope: disabled }\""
echo ""

echo "Configuration Syntax Summary:"
echo "=============================="
echo "Format: [ParentRequestType] RequestType { scope: <scope>, ref: <reference> }"
echo ""
echo "Available Scopes:"
echo "  - session: SESSION_SCOPED (retained for Maven session duration)"
echo "  - request: REQUEST_SCOPED (retained for current build request)"
echo "  - persistent: PERSISTENT (persisted across Maven invocations)"
echo "  - disabled: DISABLED (no caching performed)"
echo ""
echo "Available Reference Types:"
echo "  - soft: SOFT (cleared before OutOfMemoryError)"
echo "  - hard: HARD (never cleared by GC)"
echo "  - weak: WEAK (cleared more aggressively)"
echo "  - none: NONE (no caching, always compute)"
echo ""
echo "Key Features:"
echo "  - Both scope and ref are optional"
echo "  - Multiple selectors can match and merge"
echo "  - More specific selectors override less specific ones"
echo "  - Supports parent-child request relationships"
echo "  - Backward compatible with existing CacheMetadata"
echo "  - Early return for ProtoSession requests"
echo ""

echo "To test these configurations, run Maven with the -Dmaven.cache.config property"
echo "and observe the debug logs for cache behavior."
