#!/bin/bash

. $MBOOT_HOME/maven.functions

findAndSetMavenRepoLocal

CP=
CP=$CP:$repoLocal/maven/jars/maven-pom-converter-1.0-SNAPSHOT.jar
CP=$CP:$repoLocal/asm/jars/asm-1.3.4.jar
CP=$CP:$repoLocal/classworlds/jars/classworlds-1.1-SNAPSHOT.jar
CP=$CP:$repoLocal/commons-cli/jars/commons-cli-1.0-beta-2.jar
CP=$CP:$repoLocal/commons-httpclient/jars/commons-httpclient-2.0-rc2.jar
CP=$CP:$repoLocal/commons-lang/jars/commons-lang-1.0.1.jar
CP=$CP:$repoLocal/commons-logging/jars/commons-logging-1.0.3.jar
CP=$CP:$repoLocal/jetty/jars/jetty-4.2.10.jar
CP=$CP:$repoLocal/junit/jars/junit-3.8.1.jar
CP=$CP:$repoLocal/log4j/jars/log4j-1.1.3.jar
CP=$CP:$repoLocal/logkit/jars/logkit-1.0.1.jar
CP=$CP:$repoLocal/marmalade/jars/marmalade-core-0.1.jar
CP=$CP:$repoLocal/marmalade/jars/marmalade-el-ognl-0.1.jar
CP=$CP:$repoLocal/maven/jars/maven-artifact-2.0-SNAPSHOT.jar
CP=$CP:$repoLocal/maven/jars/maven-core-2.0-SNAPSHOT.jar
CP=$CP:$repoLocal/maven/jars/maven-model-2.0-SNAPSHOT.jar
CP=$CP:$repoLocal/maven/jars/maven-model-2.0-SNAPSHOT.jar
CP=$CP:$repoLocal/maven/jars/maven-plugin-2.0-SNAPSHOT.jar
CP=$CP:$repoLocal/maven/jars/wagon-api-0.9-SNAPSHOT.jar
CP=$CP:$repoLocal/maven/jars/wagon-http-0.9-SNAPSHOT.jar
CP=$CP:$repoLocal/modello/jars/modello-1.0-SNAPSHOT.jar
CP=$CP:$repoLocal/ognl/jars/ognl-2.5.1.jar
CP=$CP:$repoLocal/plexus/jars/plexus-0.14-SNAPSHOT.jar
CP=$CP:$repoLocal/plexus/jars/plexus-compiler-api-1.0.jar
CP=$CP:$repoLocal/plexus/jars/plexus-compiler-javac-1.0.jar
CP=$CP:$repoLocal/plexus/jars/plexus-i18n-1.0-beta-2-SNAPSHOT.jar
CP=$CP:$repoLocal/plexus/jars/plexus-jetty-httpd-1.0-SNAPSHOT.jar
CP=$CP:$repoLocal/qdox/jars/qdox-1.2.jar
CP=$CP:$repoLocal/servletapi/jars/servletapi-2.3.jar
CP=$CP:$repoLocal/surefire/jars/surefire-booter-1.0.jar
CP=$CP:$repoLocal/tagalog/jars/tagalog-0.1.jar
CP=$CP:$repoLocal/xpp3/jars/xpp3-1.1.3.3.jar
CP=$CP:$repoLocal/xstream/jars/xstream-1.0-SNAPSHOT.jar

java -classpath $CP org.apache.maven.converter.MavenPomConverterCli "$@"
