#!/bin/bash

CP=
CP=$CP:target/classes
CP=$CP:lib/plexus-0.14-SNAPSHOT.jar
CP=$CP:lib/dom4j-1.4.jar
CP=$CP:target/maven-reporeaper-1.0-SNAPSHOT.jar
CP=$CP:lib/maven-reporeaper-1.0-SNAPSHOT.jar
CP=$CP:lib/xstream-1.0-SNAPSHOT.jar
CP=$CP:lib/maven-model-2.0-SNAPSHOT.jar

java -cp $CP org.apache.maven.converter.RepoReaper "$@"
