#!/bin/sh

buildDir=target
classesDir=${buildDir}/classes
srcDir=src/main/java

rm -rf ${buildDir} > /dev/null 2>&1

mkdir -p ${classesDir}

#javac -d ${classesDir} ${srcDir}/*.java
"$JAVA_HOME/bin/javac" -g -d ${classesDir} `find ${srcDir} -name '*.java'`

( cd ${classesDir} ; "$JAVA_HOME/bin/jar" -cfm ../mboot.jar ../../manifest.txt * )

cp ${buildDir}/mboot.jar ..
