#!/bin/sh

echo "-----------------------------------------------------------------------"
echo Maven MBoot
echo "-----------------------------------------------------------------------"

if [ -z $MBOOT_HOME ]; then

echo
echo "Where would you like to install mboot? [ ~/mboot ] "
echo

read MBOOT_HOME

[ -z $MBOOT_HOME ] && MBOOT_HOME=$HOME/mboot

export MBOOT_HOME
fi

DIR=$MBOOT_HOME

echo "Installing mboot in $DIR ..."

export DIR

[ -d $DIR ] && rm -rf $DIR

mkdir $DIR

SKIP=`awk '/^__ARCHIVE_FOLLOWS__/ { print NR + 1; exit 0; }' $0`

# Take the TGZ portion of this file and pipe it to tar.
tail -n +$SKIP $0 | tar xz -C $DIR

. ${MBOOT_HOME}/maven.functions

echo "-----------------------------------------------------------------------"
echo "Installing MBoot dependencies ... "
echo "-----------------------------------------------------------------------"

downloadMBootDependencies

exit 0

__ARCHIVE_FOLLOWS__
