package org.apache.maven.doxia;

/*
 * Copyright 2001-2005 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import org.apache.maven.artifact.resolver.ArtifactResolutionException;
import org.apache.maven.execution.MavenSession;
import org.apache.maven.model.ReportPlugin;
import org.apache.maven.model.ReportSet;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.PluginConfigurationException;
import org.apache.maven.plugin.PluginManager;
import org.apache.maven.plugin.PluginManagerException;
import org.apache.maven.plugin.version.PluginVersionResolutionException;
import org.apache.maven.project.MavenProject;
import org.apache.maven.reporting.MavenReport;
import org.apache.maven.reporting.MavenReportException;
import org.codehaus.plexus.i18n.I18N;
import org.codehaus.plexus.siterenderer.Renderer;
import org.codehaus.plexus.siterenderer.RendererException;
import org.codehaus.plexus.siterenderer.sink.SiteRendererSink;
import org.codehaus.plexus.util.DirectoryScanner;
import org.codehaus.plexus.util.FileUtils;
import org.codehaus.plexus.util.IOUtil;
import org.codehaus.plexus.util.StringInputStream;
import org.codehaus.plexus.util.StringUtils;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.LineNumberReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.StringTokenizer;

/**
 * Generates the project site.
 *
 * @author <a href="mailto:evenisse@apache.org">Emmanuel Venisse</a>
 * @author <a href="mailto:vincent.siveton@gmail.com">Vincent Siveton</a>
 * @version $Id$
 * @goal site
 * @requiresDependencyResolution test
 */
public class DoxiaMojo
    extends AbstractMojo
{
    private static final String RESOURCE_DIR = "org/apache/maven/doxia";

    private static final String DEFAULT_TEMPLATE = RESOURCE_DIR + "/maven-site.vm";

    /**
     * OutputName of all project info report files generated by Maven
     */
    private static final String[] PROJECT_INFO_FILES = new String[]{"integration", "dependencies", "issue-tracking",
        "license", "mail-lists", "source-repository", "team-list"};

    /**
     * Patterns which should be excluded by default.
     */
    // TODO Push me in AbstractMojo class and remove me from AbstractMavenReport class
    private static final String[] DEFAULT_EXCLUDES = new String[]{
        // Miscellaneous typical temporary files
        "**/*~", "**/#*#", "**/.#*", "**/%*%", "**/._*",

        // CVS
        "**/CVS", "**/CVS/**", "**/.cvsignore",

        // SCCS
        "**/SCCS", "**/SCCS/**",

        // Visual SourceSafe
        "**/vssver.scc",

        // Subversion
        "**/.svn", "**/.svn/**",

        // Mac
        "**/.DS_Store"};

    /**
     * @parameter expression="${basedir}/src/site"
     * @required
     */
    private String siteDirectory;

    /**
     * @parameter alias="workingDirectory" expression="${project.build.directory}/generated-site"
     * @required
     */
    private String generatedSiteDirectory;

    /**
     * @parameter expression="${project.build.directory}/site"
     * @required
     */
    private String outputDirectory;

    /**
     * @parameter expression="${basedir}/src/site/resources"
     * @required
     */
    private File resourcesDirectory;

    /**
     * @parameter expression="${templateDirectory}
     */
    private String templateDirectory;

    /**
     * @parameter expression="${template}
     */
    private String template = DEFAULT_TEMPLATE;

    /**
     * @parameter expression="${attributes}
     */
    private Map attributes;

    /**
     * @parameter expression="${locales}
     */
    private String locales;

    /**
     * @parameter expression="${addModules}"
     * default-value="true"
     */
    private boolean addModules;

    /**
     * @parameter expression="${component.org.codehaus.plexus.siterenderer.Renderer}"
     * @required
     * @readonly
     */
    private Renderer siteRenderer;

    /**
     * @parameter expression="${component.org.codehaus.plexus.i18n.I18N}"
     * @required
     * @readonly
     */
    private I18N i18n;

    /**
     * @parameter expression="${project}"
     * @required
     * @readonly
     */
    private MavenProject project;

    /**
     * @parameter expression="${component.org.apache.maven.plugin.PluginManager}"
     * @required
     * @readonly
     */
    private PluginManager pluginManager;

    /**
     * @parameter expression="${session}"
     * @required
     * @readonly
     */
    private MavenSession session;

    private List projectInfos = new ArrayList();

    private List projectReports = new ArrayList();

    private Locale defaultLocale = Locale.ENGLISH;

    private List localesList = new ArrayList();

    /**
     * @see org.apache.maven.plugin.Mojo#execute()
     */
    public void execute()
        throws MojoExecutionException
    {
        if ( templateDirectory == null )
        {
            siteRenderer.setTemplateClassLoader( DoxiaMojo.class.getClassLoader() );
        }
        else
        {
            try
            {
                URL templateDirectoryUrl = new URL( templateDirectory );

                URL[] urls = {templateDirectoryUrl};

                URLClassLoader urlClassloader = new URLClassLoader( urls );

                siteRenderer.setTemplateClassLoader( urlClassloader );
            }
            catch ( MalformedURLException e )
            {
                throw new MojoExecutionException( templateDirectory + " isn't a valid URL.", e );
            }
        }

        List reports = getReports();

        if ( attributes == null )
        {
            attributes = new HashMap();
        }

        if ( attributes.get( "project" ) == null )
        {
            attributes.put( "project", project );
        }

        try
        {
            categorizeReports( reports );

            if ( locales == null )
            {
                localesList.add( defaultLocale );
            }
            else
            {
                StringTokenizer st = new StringTokenizer( locales, "," );

                while ( st.hasMoreTokens() )
                {
                    localesList.add( new Locale( st.nextToken().trim() ) );
                }
            }

            Locale locale;
            for ( Iterator iterator = localesList.iterator(); iterator.hasNext(); )
            {
                locale = (Locale) iterator.next();

                File localeOutputDirectory = getOuputDirectory( locale );

                // Safety
                if ( !localeOutputDirectory.exists() )
                {
                    localeOutputDirectory.mkdirs();
                }

                //Generate reports
                if ( reports != null )
                {
                    MavenReport report;
                    for ( Iterator j = reports.iterator(); j.hasNext(); )
                    {
                        report = (MavenReport) j.next();

                        getLog().info( "Generate \"" + report.getName( locale ) + "\" report." );

                        report.setReportOutputDirectory( localeOutputDirectory );

                        String outputFileName = report.getOutputName() + ".html";

                        SiteRendererSink sink = siteRenderer.createSink( new File( siteDirectory ), outputFileName,
                                                                         getSiteDescriptor( reports, locale ) );

                        report.generate( sink, locale );

                        if ( !report.isExternalReport() )
                        {
                            File outputFile = new File( localeOutputDirectory, outputFileName );

                            if ( !outputFile.getParentFile().exists() )
                            {
                                outputFile.getParentFile().mkdirs();
                            }

                            siteRenderer.generateDocument( new FileWriter( outputFile ), template, attributes, sink,
                                                           locale );
                        }
                    }
                }

                //Generate overview pages
                if ( projectInfos.size() > 0 )
                {
                    try
                    {
                        generateProjectInfoPage( getSiteDescriptor( reports, locale ), locale );
                    }
                    catch ( Exception e )
                    {
                        throw new MojoExecutionException( "An error is occurred in project info page generation.", e );
                    }
                }

                if ( projectReports.size() > 0 )
                {
                    try
                    {
                        generateProjectReportsPage( getSiteDescriptor( reports, locale ), locale );
                    }
                    catch ( Exception e )
                    {
                        throw new MojoExecutionException( "An error is occurred in project reports page generation.",
                                                          e );
                    }
                }

                // Handle the GeneratedSite Directory
                File generatedSiteFile = new File( generatedSiteDirectory );
                if ( generatedSiteFile.exists() )
                {
                    siteRenderer.render( generatedSiteFile, localeOutputDirectory, getSiteDescriptor( reports, locale ),
                                         template, attributes, locale );
                }

                // Generate static site
                File siteDirectoryFile;

                Locale firstLocale = (Locale) localesList.get( 0 );

                if ( locale.equals( firstLocale ) )
                {
                    siteDirectoryFile = new File( siteDirectory );
                }
                else
                {
                    siteDirectoryFile = new File( siteDirectory, locale.getLanguage() );
                }

                // Try to find duplicate files
                Map duplicate = new LinkedHashMap();
                if ( siteDirectoryFile.exists() )
                {
                    tryToFindDuplicates( siteDirectoryFile, duplicate );
                }
                if ( generatedSiteFile.exists() )
                {
                    tryToFindDuplicates( generatedSiteFile, duplicate );
                }

                // Exception if a file is duplicate
                if ( duplicate.size() > 0 )
                {
                    StringBuffer sb = null;
                    Map.Entry entry;
                    for ( Iterator it = duplicate.entrySet().iterator(); it.hasNext(); )
                    {
                        entry = (Map.Entry) it.next();
                        Set values = (Set) entry.getValue();

                        if ( values.size() > 1 )
                        {
                            if ( sb == null )
                            {
                                sb = new StringBuffer(
                                    "Some files are duplicates in the site directory or in the generated-site directory. " +
                                        "Review the following files:" );
                            }

                            sb.append( "\n" ).append( entry.getKey() ).append( "\n" );

                            for ( Iterator it2 = values.iterator(); it2.hasNext(); )
                            {
                                String current = (String) it2.next();
                                sb.append( "\t" ).append( current );
                                if ( it2.hasNext() )
                                {
                                    sb.append( "\n" );
                                }
                            }
                        }
                    }

                    if ( sb != null )
                    {
                        throw new MavenReportException( sb.toString() );
                    }
                }

                // Try to generate the index.html
                if ( duplicate.get( "index" ) != null )
                {
                    getLog().info( "Ignoring the index file generation." );
                }
                else
                {
                    getLog().info( "Generate an index file." );
                    generateIndexPage( getSiteDescriptor( reports, locale ), locale );
                }

                // Log if a user override a project info report file
                for ( int i = 0; i < PROJECT_INFO_FILES.length; i++ )
                {
                    if ( projectInfos.size() > 0 )
                    {
                        if ( duplicate.get( PROJECT_INFO_FILES[i] ) != null )
                        {
                            getLog().info( "Override the generated files \"" + PROJECT_INFO_FILES[i] + "\"." );
                        }
                    }
                }

                siteRenderer.render( siteDirectoryFile, localeOutputDirectory, getSiteDescriptor( reports, locale ),
                                     template, attributes, locale );

                siteRenderer.render( siteDirectoryFile, localeOutputDirectory, getSiteDescriptor( reports, locale ),
                                     template, attributes, locale );

                File cssDirectory = new File( siteDirectory, "css" );
                File imagesDirectory = new File( siteDirectory, "images" );

                // special case for backwards compatibility
                if ( cssDirectory.exists() || imagesDirectory.exists() )
                {
                    getLog().warn( "DEPRECATED: the css and images directories are deprecated, please use resources" );

                    copyDirectory( cssDirectory, new File( localeOutputDirectory, "css" ) );

                    copyDirectory( imagesDirectory, new File( localeOutputDirectory, "images" ) );
                }

                copyResources( localeOutputDirectory );

                // Copy site resources
                if ( resourcesDirectory != null && resourcesDirectory.exists() )
                {
                    copyDirectory( resourcesDirectory, localeOutputDirectory );
                }

                // Copy the generated site in parent site if needed to provide module links
                if ( addModules )
                {
                    MavenProject parentProject = project.getParent();
                    if ( parentProject != null )
                    {
/* Not working: 1) parentProject.getBasedir() returns the current basedir for some reason, so it copies inside itself
which loops forever, and 2) this might be better working as a top-level aggregation rather than pushing from the
subprojects...
                        // TODO Handle user plugin configuration
                        File parentSiteDir = new File( parentProject.getBasedir(),
                                                       parentProject.getBuild().getDirectory() + File.separator +
                                                           "site" + File.separator + project.getArtifactId() );

                        if ( !parentSiteDir.exists() )
                        {
                            parentSiteDir.mkdirs();
                        }

                        File siteDir = new File( outputDirectory );
                        FileUtils.copyDirectoryStructure( siteDir, parentSiteDir );
*/
                    }
                }
            }
        }
        catch ( MavenReportException e )
        {
            throw new MojoExecutionException( "Error during report generation", e );
        }
        catch ( RendererException e )
        {
            throw new MojoExecutionException( "Error during page generation", e );
        }
        catch ( Exception e )
        {
            throw new MojoExecutionException( "Error during site generation", e );
        }
    }

    private void categorizeReports( List reports )
        throws MojoExecutionException
    {
        for ( Iterator i = reports.iterator(); i.hasNext(); )
        {
            MavenReport report = (MavenReport) i.next();
            if ( MavenReport.CATEGORY_PROJECT_INFORMATION.equals( report.getCategoryName() ) )
            {
                projectInfos.add( report );
            }
            else if ( MavenReport.CATEGORY_PROJECT_REPORTS.equals( report.getCategoryName() ) )
            {
                projectReports.add( report );
            }
            else
            {
                throw new MojoExecutionException( "'" + report.getCategoryName() + "' category define for " +
                    report.getName( defaultLocale ) + " mojo isn't valid." );
            }
        }
    }

    private String getReportsMenu( Locale locale )
    {
        StringBuffer buffer = new StringBuffer();
        buffer.append( "<menu name=\"" );
        buffer.append( i18n.getString( "site-plugin", locale, "report.menu.projectdocumentation" ) );
        buffer.append( "\">\n" );
        buffer.append( "    <item name=\"" );
        buffer.append( i18n.getString( "site-plugin", locale, "report.menu.about" ) );
        buffer.append( " " );
        buffer.append( project.getName() );
        buffer.append( "\" href=\"/index.html\"/>\n" );

        writeReportSubMenu( projectInfos, buffer, locale, "report.menu.projectinformation", "project-info.html" );
        writeReportSubMenu( projectReports, buffer, locale, "report.menu.projectreports", "maven-reports.html" );

        buffer.append( "</menu>\n" );

        return buffer.toString();
    }

    private void writeReportSubMenu( List reports, StringBuffer buffer, Locale locale, String key,
                                     String indexFilename )
    {
        if ( reports.size() > 0 )
        {
            buffer.append( "    <item name=\"" );
            buffer.append( i18n.getString( "site-plugin", locale, key ) );
            buffer.append( "\" href=\"/" );
            buffer.append( indexFilename );
            buffer.append( "\" collapse=\"true\">\n" );

            for ( Iterator i = reports.iterator(); i.hasNext(); )
            {
                MavenReport report = (MavenReport) i.next();
                buffer.append( "        <item name=\"" );
                buffer.append( report.getName( locale ) );
                buffer.append( "\" href=\"/" );
                buffer.append( report.getOutputName() );
                buffer.append( ".html\"/>\n" );
            }

            buffer.append( "    </item>\n" );
        }
    }

    /**
     * Generate a menu for modules
     *
     * @param locale the locale wanted
     * @return a XML menu for modules
     */
    private String getModulesMenu( Locale locale )
    {
        StringBuffer buffer = new StringBuffer();
        buffer.append( "<menu name=\"" );
        buffer.append( i18n.getString( "site-plugin", locale, "report.menu.projectmodules" ) );
        buffer.append( "\">\n" );

        List modules = project.getModules();
        if ( project.getModules() != null )
        {
            for ( Iterator it = modules.iterator(); it.hasNext(); )
            {
                String module = (String) it.next();

                buffer.append( "    <item name=\"" );
                buffer.append( module );
                buffer.append( "\" href=\"" );
                buffer.append( module );
                buffer.append( "/index.html\"/>\n" );
            }
        }

        buffer.append( "</menu>\n" );

        return buffer.toString();
    }

    /**
     * Generate a menu for the parent project
     *
     * @param locale the locale wanted
     * @return a XML menu for the parent project
     */
    private String getProjectParentMenu( Locale locale )
    {
        StringBuffer buffer = new StringBuffer();
        buffer.append( "<menu name=\"" );
        buffer.append( i18n.getString( "site-plugin", locale, "report.menu.parentproject" ) );
        buffer.append( "\">\n" );

        buffer.append( "    <item name=\"" );
        buffer.append( project.getParent().getArtifactId() );
        buffer.append( "\" href=\"../index.html\"/>\n" );

        buffer.append( "</menu>\n" );

        return buffer.toString();
    }

    /**
     * @todo should only be needed once
     * 
     * @param reports  a list of reports
     * @param locale the current locale
     * @return the inpustream 
     * @throws MojoExecutionException is any 
     */
    private InputStream getSiteDescriptor( List reports, Locale locale )
        throws MojoExecutionException
    {
        File siteDescriptor = new File( siteDirectory, "site_" + locale.getLanguage() + ".xml" );

        String siteDescriptorContent;

        try
        {
            if ( siteDescriptor.exists() )
            {
                siteDescriptorContent = FileUtils.fileRead( siteDescriptor );
            }
            else
            {
                siteDescriptor = new File( siteDirectory, "site.xml" );

                if ( siteDescriptor.exists() )
                {
                    siteDescriptorContent = FileUtils.fileRead( siteDescriptor );
                }
                else
                {
                    siteDescriptorContent = IOUtil.toString( getClass().getResourceAsStream( "/default-site.xml" ) );
                }
            }
        }
        catch ( IOException e )
        {
            throw new MojoExecutionException( "The site descriptor cannot be read!", e );
        }

        Map props = new HashMap();

        if ( reports != null )
        {
            props.put( "reports", getReportsMenu( locale ) );
        }

        if ( project.getParent() != null )
        {
            props.put( "parentProject", getProjectParentMenu( locale ) );
        }

        if ( addModules )
        {
            if ( project.getModules() != null && project.getModules().size() > 0 )
            {
                /* See the Not working section, around line 460*/
                //props.put( "modules", getModulesMenu( locale ) );
            }
        }

        // TODO: interpolate ${project.*} in general

        if ( project.getName() != null )
        {
            props.put( "project.name", project.getName() );
        }
        else
        {
            props.put( "project.name", "NO_PROJECT_NAME_SET" );
        }

        if ( project.getUrl() != null )
        {
            props.put( "project.url", project.getUrl() );
        }
        else
        {
            props.put( "project.url", "NO_PROJECT_URL_SET" );
        }

        siteDescriptorContent = StringUtils.interpolate( siteDescriptorContent, props );

        return new StringInputStream( siteDescriptorContent );
    }

    /**
     * Generated an index page.
     *
     * @param siteDescriptor
     * @param locale
     * @throws Exception
     */
    private void generateIndexPage( InputStream siteDescriptor, Locale locale )
        throws Exception
    {
        String outputFileName = "index.html";

        SiteRendererSink sink = siteRenderer.createSink( new File( siteDirectory ), outputFileName, siteDescriptor );

        String title = i18n.getString( "site-plugin", locale, "report.index.title" ).trim() + " " + project.getName();

        sink.head();
        sink.title();
        sink.text( title );
        sink.title_();
        sink.head_();
        sink.body();

        sink.section1();
        sink.sectionTitle1();
        sink.text( title );
        sink.sectionTitle1_();

        sink.paragraph();
        if ( project.getDescription() != null )
        {
            // TODO How to handle i18n?
            sink.text( project.getDescription() );
        }
        else
        {
            sink.text( i18n.getString( "site-plugin", locale, "report.index.nodescription" ) );
        }
        sink.paragraph_();

        sink.body_();

        sink.flush();

        sink.close();

        siteRenderer.generateDocument( new FileWriter( new File( getOuputDirectory( locale ), outputFileName ) ),
                                       template, attributes, sink, locale );
    }

    private void generateProjectInfoPage( InputStream siteDescriptor, Locale locale )
        throws Exception
    {
        String outputFileName = "project-info.html";

        SiteRendererSink sink = siteRenderer.createSink( new File( siteDirectory ), outputFileName, siteDescriptor );

        String title = i18n.getString( "site-plugin", locale, "report.information.title" );

        sink.head();
        sink.title();
        sink.text( title );
        sink.title_();
        sink.head_();
        sink.body();

        sink.section1();
        sink.sectionTitle1();
        sink.text( title );
        sink.sectionTitle1_();

        sink.paragraph();
        sink.text( i18n.getString( "site-plugin", locale, "report.information.description1" ) + " " );
        sink.link( "http://maven.apache.org" );
        sink.text( "Maven" );
        sink.link_();
        sink.text( " " + i18n.getString( "site-plugin", locale, "report.information.description2" ) );
        sink.paragraph_();

        sink.section2();

        sink.sectionTitle2();
        sink.text( i18n.getString( "site-plugin", locale, "report.information.sectionTitle" ) );
        sink.sectionTitle2_();

        sink.table();

        sink.tableRow();
        sink.tableHeaderCell();
        sink.text( i18n.getString( "site-plugin", locale, "report.information.column.document" ) );
        sink.tableHeaderCell_();
        sink.tableHeaderCell();
        sink.text( i18n.getString( "site-plugin", locale, "report.information.column.description" ) );
        sink.tableHeaderCell_();
        sink.tableRow_();

        for ( Iterator i = projectInfos.iterator(); i.hasNext(); )
        {
            MavenReport report = (MavenReport) i.next();

            sink.tableRow();
            sink.tableCell();
            sink.link( report.getOutputName() + ".html" );
            sink.text( report.getName( locale ) );
            sink.link_();
            sink.tableCell_();
            sink.tableCell();
            sink.text( report.getDescription( locale ) );
            sink.tableCell_();
            sink.tableRow_();
        }

        sink.table_();

        sink.section2_();

        sink.section1_();

        sink.body_();

        sink.flush();

        sink.close();

        siteRenderer.generateDocument( new FileWriter( new File( getOuputDirectory( locale ), outputFileName ) ),
                                       template, attributes, sink, locale );
    }

    private void generateProjectReportsPage( InputStream siteDescriptor, Locale locale )
        throws Exception
    {
        String outputFileName = "maven-reports.html";

        SiteRendererSink sink = siteRenderer.createSink( new File( siteDirectory ), outputFileName, siteDescriptor );

        String title = i18n.getString( "site-plugin", locale, "report.project.title" );

        sink.head();
        sink.title();
        sink.text( title );
        sink.title_();
        sink.head_();
        sink.body();

        sink.section1();
        sink.sectionTitle1();
        sink.text( title );
        sink.sectionTitle1_();

        sink.paragraph();
        sink.text( i18n.getString( "site-plugin", locale, "report.project.description1" ) + " " );
        sink.link( "http://maven.apache.org" );
        sink.text( "Maven" );
        sink.link_();
        sink.text( ". " + i18n.getString( "site-plugin", locale, "report.project.description2" ) );
        sink.paragraph_();

        sink.section2();

        sink.sectionTitle2();
        sink.text( i18n.getString( "site-plugin", locale, "report.project.sectionTitle" ) );
        sink.sectionTitle2_();

        sink.table();

        sink.tableRow();
        sink.tableHeaderCell();
        sink.text( i18n.getString( "site-plugin", locale, "report.project.column.document" ) );
        sink.tableHeaderCell_();
        sink.tableHeaderCell();
        sink.text( i18n.getString( "site-plugin", locale, "report.project.column.description" ) );
        sink.tableHeaderCell_();
        sink.tableRow_();

        for ( Iterator i = projectReports.iterator(); i.hasNext(); )
        {
            MavenReport report = (MavenReport) i.next();

            sink.tableRow();
            sink.tableCell();
            sink.link( report.getOutputName() + ".html" );
            sink.text( report.getName( locale ) );
            sink.link_();
            sink.tableCell_();
            sink.tableCell();
            sink.text( report.getDescription( locale ) );
            sink.tableCell_();
            sink.tableRow_();
        }

        sink.table_();

        sink.section2_();

        sink.section1_();

        sink.body_();

        siteRenderer.generateDocument( new FileWriter( new File( getOuputDirectory( locale ), outputFileName ) ),
                                       template, attributes, sink, locale );
    }

    private void copyResources( File outputDir )
        throws Exception
    {
        InputStream resourceList = getStream( RESOURCE_DIR + "/resources.txt" );

        if ( resourceList != null )
        {
            LineNumberReader reader = new LineNumberReader( new InputStreamReader( resourceList ) );

            String line;

            while ( ( line = reader.readLine() ) != null )
            {
                InputStream is = getStream( RESOURCE_DIR + "/" + line );

                if ( is == null )
                {
                    throw new IOException(
                        "The resource " + line + " doesn't exists in " + DEFAULT_TEMPLATE + " template." );
                }

                File outputFile = new File( outputDir, line );

                if ( !outputFile.getParentFile().exists() )
                {
                    outputFile.getParentFile().mkdirs();
                }

                FileOutputStream w = new FileOutputStream( outputFile );

                IOUtil.copy( is, w );

                IOUtil.close( is );

                IOUtil.close( w );
            }
        }
    }

    private InputStream getStream( String name )
        throws Exception
    {
        return DoxiaMojo.class.getClassLoader().getResourceAsStream( name );
    }

    private void copyDirectory( File source, File destination )
        throws IOException
    {
        if ( source.exists() )
        {
            DirectoryScanner scanner = new DirectoryScanner();

            String[] includedResources = {"**/**"};

            scanner.setIncludes( includedResources );

            scanner.addDefaultExcludes();

            scanner.setBasedir( source );

            scanner.scan();

            List includedFiles = Arrays.asList( scanner.getIncludedFiles() );

            for ( Iterator j = includedFiles.iterator(); j.hasNext(); )
            {
                String name = (String) j.next();

                File sourceFile = new File( source, name );

                File destinationFile = new File( destination, name );

                FileUtils.copyFile( sourceFile, destinationFile );
            }
        }
    }

    private File getOuputDirectory( Locale locale )
    {
        if ( localesList.size() == 1 )
        {
            return new File( outputDirectory );
        }

        Locale firstLocale = (Locale) localesList.get( 0 );
        if ( locale.equals( firstLocale ) )
        {
            return new File( outputDirectory );
        }

        return new File( outputDirectory, locale.getLanguage() );
    }

    private List getReports()
        throws MojoExecutionException
    {
        // TODO: not the best solution. Perhaps a mojo tag that causes the plugin manager to populate project reports instead?

        List reportPlugins = project.getReportPlugins();

        if ( project.getModel().getReports() != null )
        {
            getLog().error(
                "DEPRECATED: Plugin contains a <reports/> section: this is IGNORED - please use <reporting/> instead." );
        }

        List reports = new ArrayList();
        if ( reportPlugins != null )
        {
            ReportPlugin reportPlugin;
            for ( Iterator it = reportPlugins.iterator(); it.hasNext(); )
            {
                reportPlugin = (ReportPlugin) it.next();

                try
                {
                    List reportSets = reportPlugin.getReportSets();

                    List reportsList = new ArrayList();

                    if ( reportSets == null || reportSets.isEmpty() )
                    {
                        reportsList = pluginManager.getReports( reportPlugin, null, project, session );

                    }
                    else
                    {
                        ReportSet reportSet;
                        for ( Iterator j = reportSets.iterator(); j.hasNext(); )
                        {
                            reportSet = (ReportSet) j.next();

                            reportsList = pluginManager.getReports( reportPlugin, reportSet, project, session );
                        }
                    }

                    reports.addAll( reportsList );
                }
                catch ( PluginManagerException e )
                {
                    throw new MojoExecutionException( "Error getting reports", e );
                }
                catch ( PluginVersionResolutionException e )
                {
                    throw new MojoExecutionException( "Error getting reports", e );
                }
                catch ( PluginConfigurationException e )
                {
                    throw new MojoExecutionException( "Error getting reports", e );
                }
                catch ( ArtifactResolutionException e )
                {
                    throw new MojoExecutionException( "Cannot find report plugin", e );
                }
            }
        }
        return reports;
    }

    /**
     * Convenience method that try to find duplicate files in sub-directories of a given directory.
     * <p>The scan is case sensitive.</p>
     *
     * @param directory the directory to scan
     * @param duplicate the map to update
     * @throws IOException if any
     */
    private static void tryToFindDuplicates( File directory, Map duplicate )
        throws IOException
    {
        String defaultExcludes = StringUtils.join( DEFAULT_EXCLUDES, "," );
        
        List siteFileNames = FileUtils.getFileNames( directory, null, defaultExcludes, false );

        String currentFileName;
        for ( Iterator it = siteFileNames.iterator(); it.hasNext(); )
        {
            currentFileName = (String) it.next();

            if ( currentFileName.lastIndexOf( File.separator ) == -1 )
            {
                // ignore files directly in the directory
                continue;
            }

            if ( currentFileName.lastIndexOf( "." ) == -1 )
            {
                // ignore files without extension
                continue;
            }

            String key = currentFileName.substring( currentFileName.indexOf( File.separator ) + 1,
                                                currentFileName.lastIndexOf( "." ) );

            String filePattern = "**/" + key + ".*";

            List duplicateFileNames = FileUtils.getFileNames( directory, filePattern, defaultExcludes, false );
            Set duplicatedFileNamesSet = (Set) duplicate.get( key.toLowerCase() );
            if ( duplicatedFileNamesSet == null )
            {
                duplicatedFileNamesSet = new HashSet();
            }

            String tmp;
            for ( Iterator it2 = duplicateFileNames.iterator(); it2.hasNext(); )
            {
                tmp = (String) it2.next();
                if ( tmp.lastIndexOf( File.separator ) == -1 )
                {
                    // ignore files directly in the directory
                    continue;
                }

                duplicatedFileNamesSet.add( directory.getAbsolutePath() + File.separator + tmp );
            }
            duplicate.put( key.toLowerCase(), duplicatedFileNamesSet );
        }
    }
}
