#!/bin/sh

buildDir=target
classesDir=${buildDir}/classes
srcDir=src/main/java

rm -rf bootstrap-mini.jar ${buildDir} > /dev/null 2>&1

mkdir -p ${classesDir}

"$JAVA_HOME/bin/javac" -g -d ${classesDir} `find ${srcDir} -name '*.java'`
ret=$?; if [ $ret != 0 ]; then exit $ret; fi

( cd ${classesDir} ; "$JAVA_HOME/bin/jar" -cfm ../../bootstrap-mini.jar ../../src/main/resources/META-INF/MANIFEST.MF * )
ret=$?; if [ $ret != 0 ]; then exit $ret; fi
