#!/bin/sh

. src/bash/maven.functions

compile . target/classes src/main

isCommandSuccessful $? "Failed compiling Maven bootstrapper classes!"

DIST=target/mboot

rm -rf $DIST > /dev/null 2>&1

mkdir -p $DIST

cp -r target/classes $DIST

cp src/bash/* $DIST

(
  cd target/mboot
  
  tar cvzf ../mboot.tar.gz *
)

cat src/sea/sea-header target/mboot.tar.gz > target/mboot-install.sh
  
chmod +x target/mboot-install.sh

