#!/bin/sh

VERSION=1.0

POM=pom.xml

usage () 
{
  echo "usage: `basename $0` [--dir=<directory>] [--jar=<name>] [--install] [--pom-install] [-v] [--leave-boot-files] [--version] [--help]" >&2
  echo "" >&2
  echo "       (ex: `basename $0` --dir=../builds/plexus --jar=plexus.jar)" >&2
  exit 1
}

dir="."
jar="default"
leaveBootFiles="0"
install="0"
pomInstall="0"

while [ $# -gt 0 ]; do
    case $1 in
	--help)
	    usage
	    ;;
	--version)
	    echo "mboot: version $VERSION"
	    exit 0
	    ;;
	-v)
	    verbose=-v
	    ;;
	--dir*)
	    if echo $1 | grep -q '=' ; then
	    	dir=`echo $1 | sed 's/^--dir=//'`
	    else
		dir=$2
		shift
	    fi		    
	    ;;
	--jar*)
	    if echo $1 | grep -q '=' ; then
	    	jar=`echo $1 | sed 's/^--jar=//'`
	    else
		jar=$2
		shift
	    fi		    
	    ;;
	--leave-boot-files)
	    leaveBootFiles=1;
	    ;;
	--install)
	    install=1;
	    ;;
	--pom-install)
	    pomInstall=1;
	    ;;
    esac

    shift
done

export MBOOT_HOME=`dirname $0`

. ${MBOOT_HOME}/maven.functions

[ ! -d $dir ] && echo "Specified directory doesn't exist!" && exit 1

[ ! -f $dir/${POM} ] && echo "No ${POM} in specified directory!" && exit 1

buildMavenProject $dir $jar $install $pomInstall $leaveBootFiles
