#!/bin/sh

VERSION=1.0

usage () 
{
  echo "usage: `basename $0` --model=<model> --version=<version> --mode=java|xsd|xpp3 --dir=<dir> --package-with-version" >&2
  echo "" >&2
  echo "       (ex: `basename $0` --model=model.mdo --version=4.0.0 --mode=java --dir=target/src)" >&2
  exit 1
}

dir="target/src/java"
model="model.mdo"
model_version=""
mode="java"
package_with_version=false

while [ $# -gt 0 ]; do
    case $1 in
	--help)
	    usage
	    ;;
	-v)
	    verbose=-v
	    ;;
	--dir*)
	    if echo $1 | grep -q '=' ; then
	    	dir=`echo $1 | sed 's/^--dir=//'`
	    else
		dir=$2
		shift
	    fi		    
	    ;;
	--version*)
	    if echo $1 | grep -q '=' ; then
	    	model_version=`echo $1 | sed 's/^--version=//'`
	    else
		model_version=$2
		shift
	    fi		    
	    ;;
	--model*)
	    if echo $1 | grep -q '=' ; then
	    	model=`echo $1 | sed 's/^--model=//'`
	    else
		model=$2
		shift
	    fi		    
	    ;;
	--mode*)
	    if echo $1 | grep -q '=' ; then
	    	mode=`echo $1 | sed 's/^--mode=//'`
	    else
		mode=$2
		shift
	    fi		    
	    ;;
	--package-with-version)
	    package_with_version=true
	    ;;
    esac

    shift
done

export MBOOT_HOME=`dirname $0`

. ${MBOOT_HOME}/maven.functions

[ ! -f $model ] && echo "Specified model doesn't exist!" && exit 1

[ ! -d $dir ] && mkdir -p $dir

findAndSetMavenRepoLocal

CP=$repoLocal/modello/jars/modello-1.0-SNAPSHOT.jar:$repoLocal/xstream/jars/xstream-1.0-SNAPSHOT.jar:$repoLocal/xpp3/jars/xpp3-1.1.3.3.jar

if $cygwin; then
  CP=`cygpath -pw "$CP"`
fi

java -classpath "$CP" org.codehaus.modello.Modello $model $mode "$dir" "$model_version" "$package_with_version"
