#!/bin/sh

VERSION=1.0

usage () 
{
  echo "usage: `basename $0` --mode=descriptor|xdoc --source=<source directory> --destination=<destination directory>" >&2
  echo "" >&2
  echo "       (ex: `basename $0` --mode=descriptor --source=src/main/java --destination=target)" >&2
  exit 1
}

dir="target/src/java"
mode="descriptor"

while [ $# -gt 0 ]; do
    case $1 in
	--help)
	    usage
	    ;;
	-v)
	    verbose=-v
	    ;;
	--destination*)
	    if echo $1 | grep -q '=' ; then
	    	destination=`echo $1 | sed 's/^--destination=//'`
	    else
		destination=$2
		shift
	    fi		    
	    ;;
	--source*)
	    if echo $1 | grep -q '=' ; then
	    	source=`echo $1 | sed 's/^--source=//'`
	    else
		source=$2
		shift
	    fi		    
	    ;;
	--mode*)
	    if echo $1 | grep -q '=' ; then
	    	mode=`echo $1 | sed 's/^--mode=//'`
	    else
		mode=$2
		shift
	    fi		    
	    ;;
	--pom*)
	    if echo $1 | grep -q '=' ; then
	    	pom=`echo $1 | sed 's/^--pom=//'`
	    else
		pom=$2
		shift
	    fi		    
	    ;;
    esac

    shift
done

export MBOOT_HOME=`dirname $0`

. ${MBOOT_HOME}/maven.functions

[ ! -d $destination ] && mkdir -p $destination

findAndSetMavenRepoLocal

CP=$repoLocal/modello/jars/modello-1.0-SNAPSHOT.jar:$repoLocal/maven/jars/maven-plugin-2.0-SNAPSHOT.jar:$repoLocal/qdox/jars/qdox-1.2.jar:$repoLocal/xstream/jars/xstream-1.0-SNAPSHOT.jar:$repoLocal/xpp3/jars/xpp3-1.1.3.3.jar

if $cygwin; then
  CP=`cygpath -pw "$CP"`
fi

java -classpath "$CP" org.apache.maven.plugin.generator.Main $mode "$source" "$destination" "$pom"
